# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ARKitFaceFilterDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARKitFaceFilterDemo
  pod 'SvrfSDK', :git => 'https://github.com/SVRF/svrf-ios-sdk.git', :tag => '1.0.0'
end
